[package]
name = "cargo-appimage"
version = "0.1.1"
authors = ["Isaac Mills <rooster0055@protonmail.com>"]
edition = "2018"
license = "GPL-3.0"
description = "Converts your crate into an AppImage"
homepage = "https://github.com/StratusFearMe21/cargo-appimage"
repository = "https://github.com/StratusFearMe21/cargo-appimage"
readme = "https://raw.githubusercontent.com/StratusFearMe21/cargo-appimage/master/README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.9.0"
anyhow = "1.0.40"
platforms = "1.1.0"
